//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgEitilt.CardCatalog.Audio.Strings.ID3v2.IV {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Fields {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Fields() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgEitilt.CardCatalog.Audio.Strings.ID3v2.IV.Fields", typeof(Fields).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other credits.
        /// </summary>
        public static string DefaultName_Credits {
            get {
                return ResourceManager.GetString("DefaultName_Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding date.
        /// </summary>
        public static string TDEN {
            get {
                return ResourceManager.GetString("TDEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original release date.
        /// </summary>
        public static string TDOR {
            get {
                return ResourceManager.GetString("TDOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording date.
        /// </summary>
        public static string TDRC {
            get {
                return ResourceManager.GetString("TDRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release date.
        /// </summary>
        public static string TDRL {
            get {
                return ResourceManager.GetString("TDRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagging date.
        /// </summary>
        public static string TDTG {
            get {
                return ResourceManager.GetString("TDTG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIME type as follows.
        /// </summary>
        public static string TFLT_MIME {
            get {
                return ResourceManager.GetString("TFLT_MIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ???? \u2013 {1}.
        /// </summary>
        public static string Time_End {
            get {
                return ResourceManager.GetString("Time_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} \u2013 {1}.
        /// </summary>
        public static string Time_Span {
            get {
                return ResourceManager.GetString("Time_Span", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} \u2013 ????.
        /// </summary>
        public static string Time_Start {
            get {
                return ResourceManager.GetString("Time_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production credits.
        /// </summary>
        public static string TIPL {
            get {
                return ResourceManager.GetString("TIPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist credits.
        /// </summary>
        public static string TMCL {
            get {
                return ResourceManager.GetString("TMCL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        public static string Value_Credits {
            get {
                return ResourceManager.GetString("Value_Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string Value_Credits_EmptyRole {
            get {
                return ResourceManager.GetString("Value_Credits_EmptyRole", resourceCulture);
            }
        }
    }
}
