//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgEitilt.CardCatalog.Audio.Strings {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ID3v2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ID3v2() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgEitilt.CardCatalog.Audio.Strings.ID3v2", typeof(ID3v2).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to reverse ID3v2 unsynchronization on a stream with an invalid byte following 0xFF.
        /// </summary>
        public static string Exception_NotUnsynchronized {
            get {
                return ResourceManager.GetString("Exception_NotUnsynchronized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to read a larger integer from ID3 stream than supported by the storage type.
        /// </summary>
        public static string Exception_ParsedIntTooLarge {
            get {
                return ResourceManager.GetString("Exception_ParsedIntTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reached end of ID3v2 stream while trying to read {0} unsynchronized bytes.
        /// </summary>
        public static string Exception_StreamEnded {
            get {
                return ResourceManager.GetString("Exception_StreamEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist portrait.
        /// </summary>
        public static string Image_Artist {
            get {
                return ResourceManager.GetString("Image_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead artist portrait.
        /// </summary>
        public static string Image_ArtistMain {
            get {
                return ResourceManager.GetString("Image_ArtistMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group picture.
        /// </summary>
        public static string Image_Band {
            get {
                return ResourceManager.GetString("Image_Band", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booklet page.
        /// </summary>
        public static string Image_Booklet {
            get {
                return ResourceManager.GetString("Image_Booklet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A brightly-colored fish.
        /// </summary>
        public static string Image_BrightFish {
            get {
                return ResourceManager.GetString("Image_BrightFish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composer portrait.
        /// </summary>
        public static string Image_Composer {
            get {
                return ResourceManager.GetString("Image_Composer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conductor portrait.
        /// </summary>
        public static string Image_Conductor {
            get {
                return ResourceManager.GetString("Image_Conductor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back cover.
        /// </summary>
        public static string Image_CoverBack {
            get {
                return ResourceManager.GetString("Image_CoverBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front cover.
        /// </summary>
        public static string Image_CoverFront {
            get {
                return ResourceManager.GetString("Image_CoverFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File icon.
        /// </summary>
        public static string Image_FileIcon {
            get {
                return ResourceManager.GetString("Image_FileIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illustration.
        /// </summary>
        public static string Image_Illustration {
            get {
                return ResourceManager.GetString("Image_Illustration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location image.
        /// </summary>
        public static string Image_Location {
            get {
                return ResourceManager.GetString("Image_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist logo.
        /// </summary>
        public static string Image_LogoArtist {
            get {
                return ResourceManager.GetString("Image_LogoArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher logo.
        /// </summary>
        public static string Image_LogoPublisher {
            get {
                return ResourceManager.GetString("Image_LogoPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium image.
        /// </summary>
        public static string Image_Medium {
            get {
                return ResourceManager.GetString("Image_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other image.
        /// </summary>
        public static string Image_Other {
            get {
                return ResourceManager.GetString("Image_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other icon.
        /// </summary>
        public static string Image_OtherIcon {
            get {
                return ResourceManager.GetString("Image_OtherIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance image.
        /// </summary>
        public static string Image_Performance {
            get {
                return ResourceManager.GetString("Image_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen capture.
        /// </summary>
        public static string Image_ScreenCapture {
            get {
                return ResourceManager.GetString("Image_ScreenCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production image.
        /// </summary>
        public static string Image_Session {
            get {
                return ResourceManager.GetString("Image_Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown image.
        /// </summary>
        public static string Image_Unknown {
            get {
                return ResourceManager.GetString("Image_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author or lyricist portrait.
        /// </summary>
        public static string Image_Writer {
            get {
                return ResourceManager.GetString("Image_Writer", resourceCulture);
            }
        }
    }
}
