//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgEitilt.CardCatalog.Audio.Strings {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ID3v1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ID3v1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgEitilt.CardCatalog.Audio.Strings.ID3v1", typeof(ID3v1).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstract.
        /// </summary>
        public static string Genre_Abstract {
            get {
                return ResourceManager.GetString("Genre_Abstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Capella.
        /// </summary>
        public static string Genre_ACapella {
            get {
                return ResourceManager.GetString("Genre_ACapella", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acid.
        /// </summary>
        public static string Genre_Acid {
            get {
                return ResourceManager.GetString("Genre_Acid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acid Jazz.
        /// </summary>
        public static string Genre_AcidJazz {
            get {
                return ResourceManager.GetString("Genre_AcidJazz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acid Punk.
        /// </summary>
        public static string Genre_AcidPunk {
            get {
                return ResourceManager.GetString("Genre_AcidPunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acoustic.
        /// </summary>
        public static string Genre_Acoustic {
            get {
                return ResourceManager.GetString("Genre_Acoustic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afro-Punk.
        /// </summary>
        public static string Genre_AfroPunk {
            get {
                return ResourceManager.GetString("Genre_AfroPunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative.
        /// </summary>
        public static string Genre_Alternative {
            get {
                return ResourceManager.GetString("Genre_Alternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlternRock.
        /// </summary>
        public static string Genre_AlternRock {
            get {
                return ResourceManager.GetString("Genre_AlternRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambient.
        /// </summary>
        public static string Genre_Ambient {
            get {
                return ResourceManager.GetString("Genre_Ambient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anime.
        /// </summary>
        public static string Genre_Anime {
            get {
                return ResourceManager.GetString("Genre_Anime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art Rock.
        /// </summary>
        public static string Genre_ArtRock {
            get {
                return ResourceManager.GetString("Genre_ArtRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audiobook.
        /// </summary>
        public static string Genre_Audiobook {
            get {
                return ResourceManager.GetString("Genre_Audiobook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Theatre.
        /// </summary>
        public static string Genre_AudioTheatre {
            get {
                return ResourceManager.GetString("Genre_AudioTheatre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avant-garde.
        /// </summary>
        public static string Genre_Avantgarde {
            get {
                return ResourceManager.GetString("Genre_Avantgarde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ballad.
        /// </summary>
        public static string Genre_Ballad {
            get {
                return ResourceManager.GetString("Genre_Ballad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baroque.
        /// </summary>
        public static string Genre_Baroque {
            get {
                return ResourceManager.GetString("Genre_Baroque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bass.
        /// </summary>
        public static string Genre_Bass {
            get {
                return ResourceManager.GetString("Genre_Bass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beat.
        /// </summary>
        public static string Genre_Beat {
            get {
                return ResourceManager.GetString("Genre_Beat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bebop.
        /// </summary>
        public static string Genre_Bebop {
            get {
                return ResourceManager.GetString("Genre_Bebop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bhangra.
        /// </summary>
        public static string Genre_Bhangra {
            get {
                return ResourceManager.GetString("Genre_Bhangra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big Band.
        /// </summary>
        public static string Genre_BigBand {
            get {
                return ResourceManager.GetString("Genre_BigBand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big Beat.
        /// </summary>
        public static string Genre_BigBeat {
            get {
                return ResourceManager.GetString("Genre_BigBeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Metal.
        /// </summary>
        public static string Genre_BlackMetal {
            get {
                return ResourceManager.GetString("Genre_BlackMetal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluegrass.
        /// </summary>
        public static string Genre_Bluegrass {
            get {
                return ResourceManager.GetString("Genre_Bluegrass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blues.
        /// </summary>
        public static string Genre_Blues {
            get {
                return ResourceManager.GetString("Genre_Blues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booty Bass.
        /// </summary>
        public static string Genre_BootyBass {
            get {
                return ResourceManager.GetString("Genre_BootyBass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakbeat.
        /// </summary>
        public static string Genre_Breakbeat {
            get {
                return ResourceManager.GetString("Genre_Breakbeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BritPop.
        /// </summary>
        public static string Genre_BritPop {
            get {
                return ResourceManager.GetString("Genre_BritPop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabaret.
        /// </summary>
        public static string Genre_Cabaret {
            get {
                return ResourceManager.GetString("Genre_Cabaret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celtic.
        /// </summary>
        public static string Genre_Celtic {
            get {
                return ResourceManager.GetString("Genre_Celtic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chamber Music.
        /// </summary>
        public static string Genre_ChamberMusic {
            get {
                return ResourceManager.GetString("Genre_ChamberMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chanson.
        /// </summary>
        public static string Genre_Chanson {
            get {
                return ResourceManager.GetString("Genre_Chanson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chillout.
        /// </summary>
        public static string Genre_Chillout {
            get {
                return ResourceManager.GetString("Genre_Chillout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chorus.
        /// </summary>
        public static string Genre_Chorus {
            get {
                return ResourceManager.GetString("Genre_Chorus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christian Gangsta Rap.
        /// </summary>
        public static string Genre_ChristianGangstaRap {
            get {
                return ResourceManager.GetString("Genre_ChristianGangstaRap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christian Rap.
        /// </summary>
        public static string Genre_ChristianRap {
            get {
                return ResourceManager.GetString("Genre_ChristianRap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christian Rock.
        /// </summary>
        public static string Genre_ChristianRock {
            get {
                return ResourceManager.GetString("Genre_ChristianRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classical.
        /// </summary>
        public static string Genre_Classical {
            get {
                return ResourceManager.GetString("Genre_Classical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic Rock.
        /// </summary>
        public static string Genre_ClassicRock {
            get {
                return ResourceManager.GetString("Genre_ClassicRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club.
        /// </summary>
        public static string Genre_Club {
            get {
                return ResourceManager.GetString("Genre_Club", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club-House.
        /// </summary>
        public static string Genre_ClubHouse {
            get {
                return ResourceManager.GetString("Genre_ClubHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comedy.
        /// </summary>
        public static string Genre_Comedy {
            get {
                return ResourceManager.GetString("Genre_Comedy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contemporary Christian.
        /// </summary>
        public static string Genre_ContempChristian {
            get {
                return ResourceManager.GetString("Genre_ContempChristian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Genre_Country {
            get {
                return ResourceManager.GetString("Genre_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crossover.
        /// </summary>
        public static string Genre_Crossover {
            get {
                return ResourceManager.GetString("Genre_Crossover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cult.
        /// </summary>
        public static string Genre_Cult {
            get {
                return ResourceManager.GetString("Genre_Cult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dance.
        /// </summary>
        public static string Genre_Dance {
            get {
                return ResourceManager.GetString("Genre_Dance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dance Hall.
        /// </summary>
        public static string Genre_DanceHall {
            get {
                return ResourceManager.GetString("Genre_DanceHall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darkwave.
        /// </summary>
        public static string Genre_Darkwave {
            get {
                return ResourceManager.GetString("Genre_Darkwave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Death Metal.
        /// </summary>
        public static string Genre_DeathMetal {
            get {
                return ResourceManager.GetString("Genre_DeathMetal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disco.
        /// </summary>
        public static string Genre_Disco {
            get {
                return ResourceManager.GetString("Genre_Disco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downtempo.
        /// </summary>
        public static string Genre_Downtempo {
            get {
                return ResourceManager.GetString("Genre_Downtempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dream.
        /// </summary>
        public static string Genre_Dream {
            get {
                return ResourceManager.GetString("Genre_Dream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drum &amp; Bass.
        /// </summary>
        public static string Genre_DrumBass {
            get {
                return ResourceManager.GetString("Genre_DrumBass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drum Solo.
        /// </summary>
        public static string Genre_DrumSolo {
            get {
                return ResourceManager.GetString("Genre_DrumSolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dub.
        /// </summary>
        public static string Genre_Dub {
            get {
                return ResourceManager.GetString("Genre_Dub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dubstep.
        /// </summary>
        public static string Genre_Dubstep {
            get {
                return ResourceManager.GetString("Genre_Dubstep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duet.
        /// </summary>
        public static string Genre_Duet {
            get {
                return ResourceManager.GetString("Genre_Duet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy Listening.
        /// </summary>
        public static string Genre_EasyListening {
            get {
                return ResourceManager.GetString("Genre_EasyListening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EBM.
        /// </summary>
        public static string Genre_EBM {
            get {
                return ResourceManager.GetString("Genre_EBM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eclectic.
        /// </summary>
        public static string Genre_Eclectic {
            get {
                return ResourceManager.GetString("Genre_Eclectic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electro.
        /// </summary>
        public static string Genre_Electro {
            get {
                return ResourceManager.GetString("Genre_Electro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electroclash.
        /// </summary>
        public static string Genre_Electroclash {
            get {
                return ResourceManager.GetString("Genre_Electroclash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronic.
        /// </summary>
        public static string Genre_Electronic {
            get {
                return ResourceManager.GetString("Genre_Electronic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emo.
        /// </summary>
        public static string Genre_Emo {
            get {
                return ResourceManager.GetString("Genre_Emo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethnic.
        /// </summary>
        public static string Genre_Ethnic {
            get {
                return ResourceManager.GetString("Genre_Ethnic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eurodance.
        /// </summary>
        public static string Genre_Eurodance {
            get {
                return ResourceManager.GetString("Genre_Eurodance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euro-House.
        /// </summary>
        public static string Genre_EuroHouse {
            get {
                return ResourceManager.GetString("Genre_EuroHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euro-Techno.
        /// </summary>
        public static string Genre_EuroTechno {
            get {
                return ResourceManager.GetString("Genre_EuroTechno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimental.
        /// </summary>
        public static string Genre_Experimental {
            get {
                return ResourceManager.GetString("Genre_Experimental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast-Fusion.
        /// </summary>
        public static string Genre_FastFusion {
            get {
                return ResourceManager.GetString("Genre_FastFusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folk.
        /// </summary>
        public static string Genre_Folk {
            get {
                return ResourceManager.GetString("Genre_Folk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folklore.
        /// </summary>
        public static string Genre_Folklore {
            get {
                return ResourceManager.GetString("Genre_Folklore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folk-Rock.
        /// </summary>
        public static string Genre_FolkRock {
            get {
                return ResourceManager.GetString("Genre_FolkRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freestyle.
        /// </summary>
        public static string Genre_Freestyle {
            get {
                return ResourceManager.GetString("Genre_Freestyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funk.
        /// </summary>
        public static string Genre_Funk {
            get {
                return ResourceManager.GetString("Genre_Funk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fusion.
        /// </summary>
        public static string Genre_Fusion {
            get {
                return ResourceManager.GetString("Genre_Fusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string Genre_Game {
            get {
                return ResourceManager.GetString("Genre_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gangsta.
        /// </summary>
        public static string Genre_Gangsta {
            get {
                return ResourceManager.GetString("Genre_Gangsta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garage.
        /// </summary>
        public static string Genre_Garage {
            get {
                return ResourceManager.GetString("Genre_Garage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garage Rock.
        /// </summary>
        public static string Genre_GarageRock {
            get {
                return ResourceManager.GetString("Genre_GarageRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G-Funk.
        /// </summary>
        public static string Genre_GFunk {
            get {
                return ResourceManager.GetString("Genre_GFunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global.
        /// </summary>
        public static string Genre_Global {
            get {
                return ResourceManager.GetString("Genre_Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goa.
        /// </summary>
        public static string Genre_Goa {
            get {
                return ResourceManager.GetString("Genre_Goa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gospel.
        /// </summary>
        public static string Genre_Gospel {
            get {
                return ResourceManager.GetString("Genre_Gospel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gothic.
        /// </summary>
        public static string Genre_Gothic {
            get {
                return ResourceManager.GetString("Genre_Gothic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gothic Rock.
        /// </summary>
        public static string Genre_GothicRock {
            get {
                return ResourceManager.GetString("Genre_GothicRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grunge.
        /// </summary>
        public static string Genre_Grunge {
            get {
                return ResourceManager.GetString("Genre_Grunge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardcore.
        /// </summary>
        public static string Genre_Hardcore {
            get {
                return ResourceManager.GetString("Genre_Hardcore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard Rock.
        /// </summary>
        public static string Genre_HardRock {
            get {
                return ResourceManager.GetString("Genre_HardRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy Metal.
        /// </summary>
        public static string Genre_HeavyMetal {
            get {
                return ResourceManager.GetString("Genre_HeavyMetal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hip-Hop.
        /// </summary>
        public static string Genre_HipHop {
            get {
                return ResourceManager.GetString("Genre_HipHop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House.
        /// </summary>
        public static string Genre_House {
            get {
                return ResourceManager.GetString("Genre_House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humor.
        /// </summary>
        public static string Genre_Humor {
            get {
                return ResourceManager.GetString("Genre_Humor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDM.
        /// </summary>
        public static string Genre_IDM {
            get {
                return ResourceManager.GetString("Genre_IDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illbient.
        /// </summary>
        public static string Genre_Illbient {
            get {
                return ResourceManager.GetString("Genre_Illbient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indie.
        /// </summary>
        public static string Genre_Indie {
            get {
                return ResourceManager.GetString("Genre_Indie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indie Rock.
        /// </summary>
        public static string Genre_IndieRock {
            get {
                return ResourceManager.GetString("Genre_IndieRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industrial.
        /// </summary>
        public static string Genre_Industrial {
            get {
                return ResourceManager.GetString("Genre_Industrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industro-Goth.
        /// </summary>
        public static string Genre_IndustroGoth {
            get {
                return ResourceManager.GetString("Genre_IndustroGoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrumental Pop.
        /// </summary>
        public static string Genre_InstrPop {
            get {
                return ResourceManager.GetString("Genre_InstrPop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrumental Rock.
        /// </summary>
        public static string Genre_InstrRock {
            get {
                return ResourceManager.GetString("Genre_InstrRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrumental.
        /// </summary>
        public static string Genre_Instrumental {
            get {
                return ResourceManager.GetString("Genre_Instrumental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jam Band.
        /// </summary>
        public static string Genre_JamBand {
            get {
                return ResourceManager.GetString("Genre_JamBand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jazz.
        /// </summary>
        public static string Genre_Jazz {
            get {
                return ResourceManager.GetString("Genre_Jazz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jazz+Funk.
        /// </summary>
        public static string Genre_JazzFunk {
            get {
                return ResourceManager.GetString("Genre_JazzFunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPop.
        /// </summary>
        public static string Genre_JPop {
            get {
                return ResourceManager.GetString("Genre_JPop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jungle.
        /// </summary>
        public static string Genre_Jungle {
            get {
                return ResourceManager.GetString("Genre_Jungle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krautrock.
        /// </summary>
        public static string Genre_Krautrock {
            get {
                return ResourceManager.GetString("Genre_Krautrock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latin.
        /// </summary>
        public static string Genre_Latin {
            get {
                return ResourceManager.GetString("Genre_Latin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leftfield.
        /// </summary>
        public static string Genre_Leftfield {
            get {
                return ResourceManager.GetString("Genre_Leftfield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo-Fi.
        /// </summary>
        public static string Genre_LoFi {
            get {
                return ResourceManager.GetString("Genre_LoFi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lounge.
        /// </summary>
        public static string Genre_Lounge {
            get {
                return ResourceManager.GetString("Genre_Lounge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Math Rock.
        /// </summary>
        public static string Genre_MathRock {
            get {
                return ResourceManager.GetString("Genre_MathRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meditative.
        /// </summary>
        public static string Genre_Meditative {
            get {
                return ResourceManager.GetString("Genre_Meditative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merengue.
        /// </summary>
        public static string Genre_Merengue {
            get {
                return ResourceManager.GetString("Genre_Merengue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metal.
        /// </summary>
        public static string Genre_Metal {
            get {
                return ResourceManager.GetString("Genre_Metal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musical.
        /// </summary>
        public static string Genre_Musical {
            get {
                return ResourceManager.GetString("Genre_Musical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Folk.
        /// </summary>
        public static string Genre_NationalFolk {
            get {
                return ResourceManager.GetString("Genre_NationalFolk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native American.
        /// </summary>
        public static string Genre_NativeAm {
            get {
                return ResourceManager.GetString("Genre_NativeAm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neoclassical.
        /// </summary>
        public static string Genre_Neoclassical {
            get {
                return ResourceManager.GetString("Genre_Neoclassical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Deutsche Welle.
        /// </summary>
        public static string Genre_NeueDeutscheWelle {
            get {
                return ResourceManager.GetString("Genre_NeueDeutscheWelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Age.
        /// </summary>
        public static string Genre_NewAge {
            get {
                return ResourceManager.GetString("Genre_NewAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Romantic.
        /// </summary>
        public static string Genre_NewRomantic {
            get {
                return ResourceManager.GetString("Genre_NewRomantic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Wave.
        /// </summary>
        public static string Genre_NewWave {
            get {
                return ResourceManager.GetString("Genre_NewWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise.
        /// </summary>
        public static string Genre_Noise {
            get {
                return ResourceManager.GetString("Genre_Noise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Genre_None {
            get {
                return ResourceManager.GetString("Genre_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu-Breakz.
        /// </summary>
        public static string Genre_NuBreakz {
            get {
                return ResourceManager.GetString("Genre_NuBreakz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oldies.
        /// </summary>
        public static string Genre_Oldies {
            get {
                return ResourceManager.GetString("Genre_Oldies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opera.
        /// </summary>
        public static string Genre_Opera {
            get {
                return ResourceManager.GetString("Genre_Opera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other genre.
        /// </summary>
        public static string Genre_Other {
            get {
                return ResourceManager.GetString("Genre_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podcast.
        /// </summary>
        public static string Genre_Podcast {
            get {
                return ResourceManager.GetString("Genre_Podcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polka.
        /// </summary>
        public static string Genre_Polka {
            get {
                return ResourceManager.GetString("Genre_Polka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polsk Punk.
        /// </summary>
        public static string Genre_PolskPunk {
            get {
                return ResourceManager.GetString("Genre_PolskPunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pop.
        /// </summary>
        public static string Genre_Pop {
            get {
                return ResourceManager.GetString("Genre_Pop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pop-Folk.
        /// </summary>
        public static string Genre_PopFolk {
            get {
                return ResourceManager.GetString("Genre_PopFolk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pop-Funk.
        /// </summary>
        public static string Genre_PopFunk {
            get {
                return ResourceManager.GetString("Genre_PopFunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porn Groove.
        /// </summary>
        public static string Genre_PornGroove {
            get {
                return ResourceManager.GetString("Genre_PornGroove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-Punk.
        /// </summary>
        public static string Genre_PostPunk {
            get {
                return ResourceManager.GetString("Genre_PostPunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-Rock.
        /// </summary>
        public static string Genre_PostRock {
            get {
                return ResourceManager.GetString("Genre_PostRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Ballad.
        /// </summary>
        public static string Genre_PowerBallad {
            get {
                return ResourceManager.GetString("Genre_PowerBallad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pranks.
        /// </summary>
        public static string Genre_Pranks {
            get {
                return ResourceManager.GetString("Genre_Pranks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primus.
        /// </summary>
        public static string Genre_Primus {
            get {
                return ResourceManager.GetString("Genre_Primus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progressive Rock.
        /// </summary>
        public static string Genre_ProgRock {
            get {
                return ResourceManager.GetString("Genre_ProgRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psybient.
        /// </summary>
        public static string Genre_Psybient {
            get {
                return ResourceManager.GetString("Genre_Psybient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psychedelic.
        /// </summary>
        public static string Genre_Psychedelic {
            get {
                return ResourceManager.GetString("Genre_Psychedelic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psychedelic Rock.
        /// </summary>
        public static string Genre_PsychRock {
            get {
                return ResourceManager.GetString("Genre_PsychRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psytrance.
        /// </summary>
        public static string Genre_Psytrance {
            get {
                return ResourceManager.GetString("Genre_Psytrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punk.
        /// </summary>
        public static string Genre_Punk {
            get {
                return ResourceManager.GetString("Genre_Punk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punk Rock.
        /// </summary>
        public static string Genre_PunkRock {
            get {
                return ResourceManager.GetString("Genre_PunkRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rap.
        /// </summary>
        public static string Genre_Rap {
            get {
                return ResourceManager.GetString("Genre_Rap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rave.
        /// </summary>
        public static string Genre_Rave {
            get {
                return ResourceManager.GetString("Genre_Rave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R&amp;B.
        /// </summary>
        public static string Genre_RB {
            get {
                return ResourceManager.GetString("Genre_RB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reggae.
        /// </summary>
        public static string Genre_Reggae {
            get {
                return ResourceManager.GetString("Genre_Reggae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retro.
        /// </summary>
        public static string Genre_Retro {
            get {
                return ResourceManager.GetString("Genre_Retro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revival.
        /// </summary>
        public static string Genre_Revival {
            get {
                return ResourceManager.GetString("Genre_Revival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhythmic Soul.
        /// </summary>
        public static string Genre_RhythmicSoul {
            get {
                return ResourceManager.GetString("Genre_RhythmicSoul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock.
        /// </summary>
        public static string Genre_Rock {
            get {
                return ResourceManager.GetString("Genre_Rock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock &amp; Roll.
        /// </summary>
        public static string Genre_RockRoll {
            get {
                return ResourceManager.GetString("Genre_RockRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salsa.
        /// </summary>
        public static string Genre_Salsa {
            get {
                return ResourceManager.GetString("Genre_Salsa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samba.
        /// </summary>
        public static string Genre_Samba {
            get {
                return ResourceManager.GetString("Genre_Samba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satire.
        /// </summary>
        public static string Genre_Satire {
            get {
                return ResourceManager.GetString("Genre_Satire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoegaze.
        /// </summary>
        public static string Genre_Shoegaze {
            get {
                return ResourceManager.GetString("Genre_Shoegaze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showtunes.
        /// </summary>
        public static string Genre_Showtunes {
            get {
                return ResourceManager.GetString("Genre_Showtunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ska.
        /// </summary>
        public static string Genre_Ska {
            get {
                return ResourceManager.GetString("Genre_Ska", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow Jam.
        /// </summary>
        public static string Genre_SlowJam {
            get {
                return ResourceManager.GetString("Genre_SlowJam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow Rock.
        /// </summary>
        public static string Genre_SlowRock {
            get {
                return ResourceManager.GetString("Genre_SlowRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonata.
        /// </summary>
        public static string Genre_Sonata {
            get {
                return ResourceManager.GetString("Genre_Sonata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soul.
        /// </summary>
        public static string Genre_Soul {
            get {
                return ResourceManager.GetString("Genre_Soul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Clip.
        /// </summary>
        public static string Genre_SoundClip {
            get {
                return ResourceManager.GetString("Genre_SoundClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soundtrack.
        /// </summary>
        public static string Genre_Soundtrack {
            get {
                return ResourceManager.GetString("Genre_Soundtrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Southern Rock.
        /// </summary>
        public static string Genre_SouthernRock {
            get {
                return ResourceManager.GetString("Genre_SouthernRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space.
        /// </summary>
        public static string Genre_Space {
            get {
                return ResourceManager.GetString("Genre_Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space Rock.
        /// </summary>
        public static string Genre_SpaceRock {
            get {
                return ResourceManager.GetString("Genre_SpaceRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech.
        /// </summary>
        public static string Genre_Speech {
            get {
                return ResourceManager.GetString("Genre_Speech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swing.
        /// </summary>
        public static string Genre_Swing {
            get {
                return ResourceManager.GetString("Genre_Swing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symphony.
        /// </summary>
        public static string Genre_Symphony {
            get {
                return ResourceManager.GetString("Genre_Symphony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symphonic Rock.
        /// </summary>
        public static string Genre_SymphRock {
            get {
                return ResourceManager.GetString("Genre_SymphRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synthpop.
        /// </summary>
        public static string Genre_Synthpop {
            get {
                return ResourceManager.GetString("Genre_Synthpop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tango.
        /// </summary>
        public static string Genre_Tango {
            get {
                return ResourceManager.GetString("Genre_Tango", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Techno.
        /// </summary>
        public static string Genre_Techno {
            get {
                return ResourceManager.GetString("Genre_Techno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Techno-Industrial.
        /// </summary>
        public static string Genre_TechnoIndustr {
            get {
                return ResourceManager.GetString("Genre_TechnoIndustr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terror.
        /// </summary>
        public static string Genre_Terror {
            get {
                return ResourceManager.GetString("Genre_Terror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thrash Metal.
        /// </summary>
        public static string Genre_ThrashMetal {
            get {
                return ResourceManager.GetString("Genre_ThrashMetal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 40.
        /// </summary>
        public static string Genre_Top40 {
            get {
                return ResourceManager.GetString("Genre_Top40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailer.
        /// </summary>
        public static string Genre_Trailer {
            get {
                return ResourceManager.GetString("Genre_Trailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trance.
        /// </summary>
        public static string Genre_Trance {
            get {
                return ResourceManager.GetString("Genre_Trance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tribal.
        /// </summary>
        public static string Genre_Tribal {
            get {
                return ResourceManager.GetString("Genre_Tribal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip-Hop.
        /// </summary>
        public static string Genre_TripHop {
            get {
                return ResourceManager.GetString("Genre_TripHop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trop Rock.
        /// </summary>
        public static string Genre_TropRock {
            get {
                return ResourceManager.GetString("Genre_TropRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown genre: {0}.
        /// </summary>
        public static string Genre_Unknown {
            get {
                return ResourceManager.GetString("Genre_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vocal.
        /// </summary>
        public static string Genre_Vocal {
            get {
                return ResourceManager.GetString("Genre_Vocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Music.
        /// </summary>
        public static string Genre_WorldMusic {
            get {
                return ResourceManager.GetString("Genre_WorldMusic", resourceCulture);
            }
        }
    }
}
