//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgEitilt.CardCatalog.Audio.Strings.ID3v2 {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Fields {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Fields() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgEitilt.CardCatalog.Audio.Strings.ID3v2.Fields", typeof(Fields).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string COMM {
            get {
                return ResourceManager.GetString("COMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown length.
        /// </summary>
        public static string DefaultName_Length {
            get {
                return ResourceManager.GetString("DefaultName_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown number.
        /// </summary>
        public static string DefaultName_Number {
            get {
                return ResourceManager.GetString("DefaultName_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown text.
        /// </summary>
        public static string DefaultName_Text {
            get {
                return ResourceManager.GetString("DefaultName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown time.
        /// </summary>
        public static string DefaultName_Time {
            get {
                return ResourceManager.GetString("DefaultName_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown URL.
        /// </summary>
        public static string DefaultName_Url {
            get {
                return ResourceManager.GetString("DefaultName_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play count.
        /// </summary>
        public static string PCNT {
            get {
                return ResourceManager.GetString("PCNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        public static string Subtitle_Language {
            get {
                return ResourceManager.GetString("Subtitle_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string TALB {
            get {
                return ResourceManager.GetString("TALB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beats per minute.
        /// </summary>
        public static string TBPM {
            get {
                return ResourceManager.GetString("TBPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string TCAT {
            get {
                return ResourceManager.GetString("TCAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation (iTunes).
        /// </summary>
        public static string TCMP {
            get {
                return ResourceManager.GetString("TCMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not part of a compilation.
        /// </summary>
        public static string TCMP_0 {
            get {
                return ResourceManager.GetString("TCMP_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From a compilation album.
        /// </summary>
        public static string TCMP_1 {
            get {
                return ResourceManager.GetString("TCMP_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composer.
        /// </summary>
        public static string TCOM {
            get {
                return ResourceManager.GetString("TCOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string TCON {
            get {
                return ResourceManager.GetString("TCON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover.
        /// </summary>
        public static string TCON_CR {
            get {
                return ResourceManager.GetString("TCON_CR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remix.
        /// </summary>
        public static string TCON_RX {
            get {
                return ResourceManager.GetString("TCON_RX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string TCOP {
            get {
                return ResourceManager.GetString("TCOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \u00A9 {0}.
        /// </summary>
        public static string TCOP_Value {
            get {
                return ResourceManager.GetString("TCOP_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string TDES {
            get {
                return ResourceManager.GetString("TDES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist delay.
        /// </summary>
        public static string TDLY {
            get {
                return ResourceManager.GetString("TDLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoder.
        /// </summary>
        public static string TENC {
            get {
                return ResourceManager.GetString("TENC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string TEXT {
            get {
                return ResourceManager.GetString("TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio encoding.
        /// </summary>
        public static string TFLT {
            get {
                return ResourceManager.GetString("TFLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPEG audio.
        /// </summary>
        public static string TFLT_MPG {
            get {
                return ResourceManager.GetString("TFLT_MPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPEG 1/2 layer I.
        /// </summary>
        public static string TFLT_MPG_1 {
            get {
                return ResourceManager.GetString("TFLT_MPG_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPEG 1/2 layer II.
        /// </summary>
        public static string TFLT_MPG_2 {
            get {
                return ResourceManager.GetString("TFLT_MPG_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPEG 2.5.
        /// </summary>
        public static string TFLT_MPG_2_5 {
            get {
                return ResourceManager.GetString("TFLT_MPG_2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPEG 1/2 layer III.
        /// </summary>
        public static string TFLT_MPG_3 {
            get {
                return ResourceManager.GetString("TFLT_MPG_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced audio compression (MPEG).
        /// </summary>
        public static string TFLT_MPG_AAC {
            get {
                return ResourceManager.GetString("TFLT_MPG_AAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse code modulated audio.
        /// </summary>
        public static string TFLT_PCM {
            get {
                return ResourceManager.GetString("TFLT_PCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transform-domain weighted interleave vector quantisation.
        /// </summary>
        public static string TFLT_VQF {
            get {
                return ResourceManager.GetString("TFLT_VQF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album ID.
        /// </summary>
        public static string TGID {
            get {
                return ResourceManager.GetString("TGID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\u2013{1}.
        /// </summary>
        public static string Time_Range {
            get {
                return ResourceManager.GetString("Time_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string Time_Single {
            get {
                return ResourceManager.GetString("Time_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Time_Unknown {
            get {
                return ResourceManager.GetString("Time_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work.
        /// </summary>
        public static string TIT1 {
            get {
                return ResourceManager.GetString("TIT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TIT2 {
            get {
                return ResourceManager.GetString("TIT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle.
        /// </summary>
        public static string TIT3 {
            get {
                return ResourceManager.GetString("TIT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string TKEY {
            get {
                return ResourceManager.GetString("TKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off key.
        /// </summary>
        public static string TKEY_OffKey {
            get {
                return ResourceManager.GetString("TKEY_OffKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        public static string TKWD {
            get {
                return ResourceManager.GetString("TKWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string TLAN {
            get {
                return ResourceManager.GetString("TLAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string TLEN {
            get {
                return ResourceManager.GetString("TLEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original medium.
        /// </summary>
        public static string TMED {
            get {
                return ResourceManager.GetString("TMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown analog source.
        /// </summary>
        public static string TMED_ANA {
            get {
                return ResourceManager.GetString("TMED_ANA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8-track tape cassette.
        /// </summary>
        public static string TMED_ANA_8CA {
            get {
                return ResourceManager.GetString("TMED_ANA_8CA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wax cylinder.
        /// </summary>
        public static string TMED_ANA_WAC {
            get {
                return ResourceManager.GetString("TMED_ANA_WAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compact disk.
        /// </summary>
        public static string TMED_CD {
            get {
                return ResourceManager.GetString("TMED_CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analog transfer from CD.
        /// </summary>
        public static string TMED_CD_A {
            get {
                return ResourceManager.GetString("TMED_CD_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compact disk (SPARS AAD).
        /// </summary>
        public static string TMED_CD_AA {
            get {
                return ResourceManager.GetString("TMED_CD_AA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compact disk (SPARS ADD).
        /// </summary>
        public static string TMED_CD_AD {
            get {
                return ResourceManager.GetString("TMED_CD_AD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compact disk (SPARS DDD).
        /// </summary>
        public static string TMED_CD_DD {
            get {
                return ResourceManager.GetString("TMED_CD_DD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAT cassette.
        /// </summary>
        public static string TMED_DAT {
            get {
                return ResourceManager.GetString("TMED_DAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAT standard: 48 kHz/16 bits, linear.
        /// </summary>
        public static string TMED_DAT_1 {
            get {
                return ResourceManager.GetString("TMED_DAT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAT mode 2: 32 kHz/16 bits, linear.
        /// </summary>
        public static string TMED_DAT_2 {
            get {
                return ResourceManager.GetString("TMED_DAT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAT mode 3: 32 kHz/12 bits, non-linear, low speed.
        /// </summary>
        public static string TMED_DAT_3 {
            get {
                return ResourceManager.GetString("TMED_DAT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAT mode 4: 32 kHz/12 bits, 4 channels.
        /// </summary>
        public static string TMED_DAT_4 {
            get {
                return ResourceManager.GetString("TMED_DAT_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAT mode 5: 44.1 kHz/16 bits, linear.
        /// </summary>
        public static string TMED_DAT_5 {
            get {
                return ResourceManager.GetString("TMED_DAT_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAT mode 6: 44.1 kHz/16 bits, &apos;wide track&apos; play.
        /// </summary>
        public static string TMED_DAT_6 {
            get {
                return ResourceManager.GetString("TMED_DAT_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analog transfer from DAT cassette.
        /// </summary>
        public static string TMED_DAT_A {
            get {
                return ResourceManager.GetString("TMED_DAT_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCC cassette.
        /// </summary>
        public static string TMED_DCC {
            get {
                return ResourceManager.GetString("TMED_DCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analog transfer from DCC cassette.
        /// </summary>
        public static string TMED_DCC_A {
            get {
                return ResourceManager.GetString("TMED_DCC_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown digital source.
        /// </summary>
        public static string TMED_DIG {
            get {
                return ResourceManager.GetString("TMED_DIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analog transfer from digital.
        /// </summary>
        public static string TMED_DIG_A {
            get {
                return ResourceManager.GetString("TMED_DIG_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVD.
        /// </summary>
        public static string TMED_DVD {
            get {
                return ResourceManager.GetString("TMED_DVD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analog transfer from DVD.
        /// </summary>
        public static string TMED_DVD_A {
            get {
                return ResourceManager.GetString("TMED_DVD_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISDN telephone.
        /// </summary>
        public static string TMED_I {
            get {
                return ResourceManager.GetString("TMED_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laserdisk.
        /// </summary>
        public static string TMED_LD {
            get {
                return ResourceManager.GetString("TMED_LD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analog transfer from laserdisk.
        /// </summary>
        public static string TMED_LD_A {
            get {
                return ResourceManager.GetString("TMED_LD_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tape cassette.
        /// </summary>
        public static string TMED_MC {
            get {
                return ResourceManager.GetString("TMED_MC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.75 cm/s cassette (standard).
        /// </summary>
        public static string TMED_MC_4 {
            get {
                return ResourceManager.GetString("TMED_MC_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.5 cm/s cassette.
        /// </summary>
        public static string TMED_MC_9 {
            get {
                return ResourceManager.GetString("TMED_MC_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type I (standard, ferric) cassette.
        /// </summary>
        public static string TMED_MC_I {
            get {
                return ResourceManager.GetString("TMED_MC_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type II (chrome) cassette.
        /// </summary>
        public static string TMED_MC_II {
            get {
                return ResourceManager.GetString("TMED_MC_II", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type III (ferric chrome) cassette.
        /// </summary>
        public static string TMED_MC_III {
            get {
                return ResourceManager.GetString("TMED_MC_III", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type IV (metal) cassette.
        /// </summary>
        public static string TMED_MC_IV {
            get {
                return ResourceManager.GetString("TMED_MC_IV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiniDisc.
        /// </summary>
        public static string TMED_MD {
            get {
                return ResourceManager.GetString("TMED_MD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analog transfer from MiniDisc.
        /// </summary>
        public static string TMED_MD_A {
            get {
                return ResourceManager.GetString("TMED_MD_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio.
        /// </summary>
        public static string TMED_RAD {
            get {
                return ResourceManager.GetString("TMED_RAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AM radio.
        /// </summary>
        public static string TMED_RAD_AM {
            get {
                return ResourceManager.GetString("TMED_RAD_AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FM radio.
        /// </summary>
        public static string TMED_RAD_FM {
            get {
                return ResourceManager.GetString("TMED_RAD_FM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longwave radio.
        /// </summary>
        public static string TMED_RAD_LW {
            get {
                return ResourceManager.GetString("TMED_RAD_LW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium wave radio.
        /// </summary>
        public static string TMED_RAD_MW {
            get {
                return ResourceManager.GetString("TMED_RAD_MW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tape cassette reel.
        /// </summary>
        public static string TMED_REE {
            get {
                return ResourceManager.GetString("TMED_REE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19 cm/s cassette reel.
        /// </summary>
        public static string TMED_REE_19 {
            get {
                return ResourceManager.GetString("TMED_REE_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 38 cm/s cassette reel.
        /// </summary>
        public static string TMED_REE_38 {
            get {
                return ResourceManager.GetString("TMED_REE_38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 76 cm/s cassette reel.
        /// </summary>
        public static string TMED_REE_76 {
            get {
                return ResourceManager.GetString("TMED_REE_76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.5 cm/s cassette reel.
        /// </summary>
        public static string TMED_REE_9 {
            get {
                return ResourceManager.GetString("TMED_REE_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type I (standard, ferric) cassette reel.
        /// </summary>
        public static string TMED_REE_I {
            get {
                return ResourceManager.GetString("TMED_REE_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type II (chrome) cassette reel.
        /// </summary>
        public static string TMED_REE_II {
            get {
                return ResourceManager.GetString("TMED_REE_II", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type III (ferric chrome) cassette reel.
        /// </summary>
        public static string TMED_REE_III {
            get {
                return ResourceManager.GetString("TMED_REE_III", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type IV (metal) cassette reel.
        /// </summary>
        public static string TMED_REE_IV {
            get {
                return ResourceManager.GetString("TMED_REE_IV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string TMED_TEL {
            get {
                return ResourceManager.GetString("TMED_TEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISDN telephone.
        /// </summary>
        public static string TMED_TEL_I {
            get {
                return ResourceManager.GetString("TMED_TEL_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turntable record.
        /// </summary>
        public static string TMED_TT {
            get {
                return ResourceManager.GetString("TMED_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 33.33 rpm record.
        /// </summary>
        public static string TMED_TT_33 {
            get {
                return ResourceManager.GetString("TMED_TT_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 45 rpm record.
        /// </summary>
        public static string TMED_TT_45 {
            get {
                return ResourceManager.GetString("TMED_TT_45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 71.29 rpm record.
        /// </summary>
        public static string TMED_TT_71 {
            get {
                return ResourceManager.GetString("TMED_TT_71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 76.59 rpm record.
        /// </summary>
        public static string TMED_TT_76 {
            get {
                return ResourceManager.GetString("TMED_TT_76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 78.26 rpm record.
        /// </summary>
        public static string TMED_TT_78 {
            get {
                return ResourceManager.GetString("TMED_TT_78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80 rpm record.
        /// </summary>
        public static string TMED_TT_80 {
            get {
                return ResourceManager.GetString("TMED_TT_80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Television.
        /// </summary>
        public static string TMED_TV {
            get {
                return ResourceManager.GetString("TMED_TV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Television (NTSC).
        /// </summary>
        public static string TMED_TV_NTSC {
            get {
                return ResourceManager.GetString("TMED_TV_NTSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Television (PAL).
        /// </summary>
        public static string TMED_TV_PAL {
            get {
                return ResourceManager.GetString("TMED_TV_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Television (SECAM).
        /// </summary>
        public static string TMED_TV_SECAM {
            get {
                return ResourceManager.GetString("TMED_TV_SECAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string TMED_VID {
            get {
                return ResourceManager.GetString("TMED_VID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BETAMAX tape.
        /// </summary>
        public static string TMED_VID_BETA {
            get {
                return ResourceManager.GetString("TMED_VID_BETA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video (NTSC).
        /// </summary>
        public static string TMED_VID_NTSC {
            get {
                return ResourceManager.GetString("TMED_VID_NTSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video (PAL).
        /// </summary>
        public static string TMED_VID_PAL {
            get {
                return ResourceManager.GetString("TMED_VID_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video (SECAM).
        /// </summary>
        public static string TMED_VID_SECAM {
            get {
                return ResourceManager.GetString("TMED_VID_SECAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S-VHS tape.
        /// </summary>
        public static string TMED_VID_SVHS {
            get {
                return ResourceManager.GetString("TMED_VID_SVHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VHS tape.
        /// </summary>
        public static string TMED_VID_VHS {
            get {
                return ResourceManager.GetString("TMED_VID_VHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mood.
        /// </summary>
        public static string TMOO {
            get {
                return ResourceManager.GetString("TMOO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original album.
        /// </summary>
        public static string TOAL {
            get {
                return ResourceManager.GetString("TOAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original filename.
        /// </summary>
        public static string TOFN {
            get {
                return ResourceManager.GetString("TOFN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original author.
        /// </summary>
        public static string TOLY {
            get {
                return ResourceManager.GetString("TOLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original artist.
        /// </summary>
        public static string TOPE {
            get {
                return ResourceManager.GetString("TOPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string TOWN {
            get {
                return ResourceManager.GetString("TOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string TPE1 {
            get {
                return ResourceManager.GetString("TPE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album artist.
        /// </summary>
        public static string TPE2 {
            get {
                return ResourceManager.GetString("TPE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conductor.
        /// </summary>
        public static string TPE3 {
            get {
                return ResourceManager.GetString("TPE3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remixer.
        /// </summary>
        public static string TPE4 {
            get {
                return ResourceManager.GetString("TPE4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk number.
        /// </summary>
        public static string TPOS {
            get {
                return ResourceManager.GetString("TPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production copyright.
        /// </summary>
        public static string TPRO {
            get {
                return ResourceManager.GetString("TPRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \u2117 {0}.
        /// </summary>
        public static string TPRO_Value {
            get {
                return ResourceManager.GetString("TPRO_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string TPUB {
            get {
                return ResourceManager.GetString("TPUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track number.
        /// </summary>
        public static string TRCK {
            get {
                return ResourceManager.GetString("TRCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station name.
        /// </summary>
        public static string TRSN {
            get {
                return ResourceManager.GetString("TRSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station owner.
        /// </summary>
        public static string TRSO {
            get {
                return ResourceManager.GetString("TRSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album artist sort order.
        /// </summary>
        public static string TSO2 {
            get {
                return ResourceManager.GetString("TSO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album sort order.
        /// </summary>
        public static string TSOA {
            get {
                return ResourceManager.GetString("TSOA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composer sort order.
        /// </summary>
        public static string TSOC {
            get {
                return ResourceManager.GetString("TSOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist sort order.
        /// </summary>
        public static string TSOP {
            get {
                return ResourceManager.GetString("TSOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title sort order.
        /// </summary>
        public static string TSOT {
            get {
                return ResourceManager.GetString("TSOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording ISRC.
        /// </summary>
        public static string TSRC {
            get {
                return ResourceManager.GetString("TSRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding settings.
        /// </summary>
        public static string TSSE {
            get {
                return ResourceManager.GetString("TSSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk title.
        /// </summary>
        public static string TSST {
            get {
                return ResourceManager.GetString("TSST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other text.
        /// </summary>
        public static string TXXX {
            get {
                return ResourceManager.GetString("TXXX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique ID.
        /// </summary>
        public static string UFID {
            get {
                return ResourceManager.GetString("UFID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyrics.
        /// </summary>
        public static string USLT {
            get {
                return ResourceManager.GetString("USLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1}.
        /// </summary>
        public static string ValueFormat_NumberOf {
            get {
                return ResourceManager.GetString("ValueFormat_NumberOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchasing information.
        /// </summary>
        public static string WCOM {
            get {
                return ResourceManager.GetString("WCOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright information.
        /// </summary>
        public static string WCOP {
            get {
                return ResourceManager.GetString("WCOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed.
        /// </summary>
        public static string WFED {
            get {
                return ResourceManager.GetString("WFED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official website.
        /// </summary>
        public static string WOAF {
            get {
                return ResourceManager.GetString("WOAF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist homepage.
        /// </summary>
        public static string WOAR {
            get {
                return ResourceManager.GetString("WOAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source website.
        /// </summary>
        public static string WOAS {
            get {
                return ResourceManager.GetString("WOAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio station homepage.
        /// </summary>
        public static string WORS {
            get {
                return ResourceManager.GetString("WORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment website.
        /// </summary>
        public static string WPAY {
            get {
                return ResourceManager.GetString("WPAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher homepage.
        /// </summary>
        public static string WPUB {
            get {
                return ResourceManager.GetString("WPUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other URL.
        /// </summary>
        public static string WXXX {
            get {
                return ResourceManager.GetString("WXXX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album sort order (alternate).
        /// </summary>
        public static string XSOA {
            get {
                return ResourceManager.GetString("XSOA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist sort order (alternate).
        /// </summary>
        public static string XSOP {
            get {
                return ResourceManager.GetString("XSOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title sort order (alternate).
        /// </summary>
        public static string XSOT {
            get {
                return ResourceManager.GetString("XSOT", resourceCulture);
            }
        }
    }
}
