//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgEitilt.CardCatalog.Audio.Strings.ID3v2 {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Images {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Images() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgEitilt.CardCatalog.Audio.Strings.ID3v2.Images", typeof(Images).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist portrait.
        /// </summary>
        public static string Artist {
            get {
                return ResourceManager.GetString("Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead artist portrait.
        /// </summary>
        public static string ArtistMain {
            get {
                return ResourceManager.GetString("ArtistMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group picture.
        /// </summary>
        public static string Band {
            get {
                return ResourceManager.GetString("Band", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booklet page.
        /// </summary>
        public static string Booklet {
            get {
                return ResourceManager.GetString("Booklet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A brightly-colored fish.
        /// </summary>
        public static string BrightFish {
            get {
                return ResourceManager.GetString("BrightFish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composer portrait.
        /// </summary>
        public static string Composer {
            get {
                return ResourceManager.GetString("Composer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conductor portrait.
        /// </summary>
        public static string Conductor {
            get {
                return ResourceManager.GetString("Conductor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back cover.
        /// </summary>
        public static string CoverBack {
            get {
                return ResourceManager.GetString("CoverBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front cover.
        /// </summary>
        public static string CoverFront {
            get {
                return ResourceManager.GetString("CoverFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File icon.
        /// </summary>
        public static string FileIcon {
            get {
                return ResourceManager.GetString("FileIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illustration.
        /// </summary>
        public static string Illustration {
            get {
                return ResourceManager.GetString("Illustration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location image.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist logo.
        /// </summary>
        public static string LogoArtist {
            get {
                return ResourceManager.GetString("LogoArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher logo.
        /// </summary>
        public static string LogoPublisher {
            get {
                return ResourceManager.GetString("LogoPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium image.
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other image.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other icon.
        /// </summary>
        public static string OtherIcon {
            get {
                return ResourceManager.GetString("OtherIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance image.
        /// </summary>
        public static string Performance {
            get {
                return ResourceManager.GetString("Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen capture.
        /// </summary>
        public static string ScreenCapture {
            get {
                return ResourceManager.GetString("ScreenCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production image.
        /// </summary>
        public static string Session {
            get {
                return ResourceManager.GetString("Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown image.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author or lyricist portrait.
        /// </summary>
        public static string Writer {
            get {
                return ResourceManager.GetString("Writer", resourceCulture);
            }
        }
    }
}
