//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgEitilt.CardCatalog.Audio.Strings.ID3v1 {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Genres {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Genres() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgEitilt.CardCatalog.Audio.Strings.ID3v1.Genres", typeof(Genres).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstract.
        /// </summary>
        public static string Abstract {
            get {
                return ResourceManager.GetString("Abstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Capella.
        /// </summary>
        public static string ACapella {
            get {
                return ResourceManager.GetString("ACapella", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acid.
        /// </summary>
        public static string Acid {
            get {
                return ResourceManager.GetString("Acid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acid Jazz.
        /// </summary>
        public static string AcidJazz {
            get {
                return ResourceManager.GetString("AcidJazz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acid Punk.
        /// </summary>
        public static string AcidPunk {
            get {
                return ResourceManager.GetString("AcidPunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acoustic.
        /// </summary>
        public static string Acoustic {
            get {
                return ResourceManager.GetString("Acoustic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afro-Punk.
        /// </summary>
        public static string AfroPunk {
            get {
                return ResourceManager.GetString("AfroPunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative.
        /// </summary>
        public static string Alternative {
            get {
                return ResourceManager.GetString("Alternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlternRock.
        /// </summary>
        public static string AlternRock {
            get {
                return ResourceManager.GetString("AlternRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambient.
        /// </summary>
        public static string Ambient {
            get {
                return ResourceManager.GetString("Ambient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anime.
        /// </summary>
        public static string Anime {
            get {
                return ResourceManager.GetString("Anime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art Rock.
        /// </summary>
        public static string ArtRock {
            get {
                return ResourceManager.GetString("ArtRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audiobook.
        /// </summary>
        public static string Audiobook {
            get {
                return ResourceManager.GetString("Audiobook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Theatre.
        /// </summary>
        public static string AudioTheatre {
            get {
                return ResourceManager.GetString("AudioTheatre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avant-garde.
        /// </summary>
        public static string Avantgarde {
            get {
                return ResourceManager.GetString("Avantgarde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ballad.
        /// </summary>
        public static string Ballad {
            get {
                return ResourceManager.GetString("Ballad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baroque.
        /// </summary>
        public static string Baroque {
            get {
                return ResourceManager.GetString("Baroque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bass.
        /// </summary>
        public static string Bass {
            get {
                return ResourceManager.GetString("Bass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beat.
        /// </summary>
        public static string Beat {
            get {
                return ResourceManager.GetString("Beat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bebop.
        /// </summary>
        public static string Bebop {
            get {
                return ResourceManager.GetString("Bebop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bhangra.
        /// </summary>
        public static string Bhangra {
            get {
                return ResourceManager.GetString("Bhangra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big Band.
        /// </summary>
        public static string BigBand {
            get {
                return ResourceManager.GetString("BigBand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big Beat.
        /// </summary>
        public static string BigBeat {
            get {
                return ResourceManager.GetString("BigBeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Metal.
        /// </summary>
        public static string BlackMetal {
            get {
                return ResourceManager.GetString("BlackMetal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluegrass.
        /// </summary>
        public static string Bluegrass {
            get {
                return ResourceManager.GetString("Bluegrass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blues.
        /// </summary>
        public static string Blues {
            get {
                return ResourceManager.GetString("Blues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booty Bass.
        /// </summary>
        public static string BootyBass {
            get {
                return ResourceManager.GetString("BootyBass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakbeat.
        /// </summary>
        public static string Breakbeat {
            get {
                return ResourceManager.GetString("Breakbeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BritPop.
        /// </summary>
        public static string BritPop {
            get {
                return ResourceManager.GetString("BritPop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabaret.
        /// </summary>
        public static string Cabaret {
            get {
                return ResourceManager.GetString("Cabaret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celtic.
        /// </summary>
        public static string Celtic {
            get {
                return ResourceManager.GetString("Celtic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chamber Music.
        /// </summary>
        public static string ChamberMusic {
            get {
                return ResourceManager.GetString("ChamberMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chanson.
        /// </summary>
        public static string Chanson {
            get {
                return ResourceManager.GetString("Chanson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chillout.
        /// </summary>
        public static string Chillout {
            get {
                return ResourceManager.GetString("Chillout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chorus.
        /// </summary>
        public static string Chorus {
            get {
                return ResourceManager.GetString("Chorus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christian Gangsta Rap.
        /// </summary>
        public static string ChristianGangstaRap {
            get {
                return ResourceManager.GetString("ChristianGangstaRap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christian Rap.
        /// </summary>
        public static string ChristianRap {
            get {
                return ResourceManager.GetString("ChristianRap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christian Rock.
        /// </summary>
        public static string ChristianRock {
            get {
                return ResourceManager.GetString("ChristianRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classical.
        /// </summary>
        public static string Classical {
            get {
                return ResourceManager.GetString("Classical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic Rock.
        /// </summary>
        public static string ClassicRock {
            get {
                return ResourceManager.GetString("ClassicRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club.
        /// </summary>
        public static string Club {
            get {
                return ResourceManager.GetString("Club", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club-House.
        /// </summary>
        public static string ClubHouse {
            get {
                return ResourceManager.GetString("ClubHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comedy.
        /// </summary>
        public static string Comedy {
            get {
                return ResourceManager.GetString("Comedy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contemporary Christian.
        /// </summary>
        public static string ContempChristian {
            get {
                return ResourceManager.GetString("ContempChristian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crossover.
        /// </summary>
        public static string Crossover {
            get {
                return ResourceManager.GetString("Crossover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cult.
        /// </summary>
        public static string Cult {
            get {
                return ResourceManager.GetString("Cult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dance.
        /// </summary>
        public static string Dance {
            get {
                return ResourceManager.GetString("Dance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dance Hall.
        /// </summary>
        public static string DanceHall {
            get {
                return ResourceManager.GetString("DanceHall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darkwave.
        /// </summary>
        public static string Darkwave {
            get {
                return ResourceManager.GetString("Darkwave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Death Metal.
        /// </summary>
        public static string DeathMetal {
            get {
                return ResourceManager.GetString("DeathMetal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disco.
        /// </summary>
        public static string Disco {
            get {
                return ResourceManager.GetString("Disco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downtempo.
        /// </summary>
        public static string Downtempo {
            get {
                return ResourceManager.GetString("Downtempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dream.
        /// </summary>
        public static string Dream {
            get {
                return ResourceManager.GetString("Dream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drum &amp; Bass.
        /// </summary>
        public static string DrumBass {
            get {
                return ResourceManager.GetString("DrumBass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drum Solo.
        /// </summary>
        public static string DrumSolo {
            get {
                return ResourceManager.GetString("DrumSolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dub.
        /// </summary>
        public static string Dub {
            get {
                return ResourceManager.GetString("Dub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dubstep.
        /// </summary>
        public static string Dubstep {
            get {
                return ResourceManager.GetString("Dubstep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duet.
        /// </summary>
        public static string Duet {
            get {
                return ResourceManager.GetString("Duet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy Listening.
        /// </summary>
        public static string EasyListening {
            get {
                return ResourceManager.GetString("EasyListening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EBM.
        /// </summary>
        public static string EBM {
            get {
                return ResourceManager.GetString("EBM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eclectic.
        /// </summary>
        public static string Eclectic {
            get {
                return ResourceManager.GetString("Eclectic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electro.
        /// </summary>
        public static string Electro {
            get {
                return ResourceManager.GetString("Electro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electroclash.
        /// </summary>
        public static string Electroclash {
            get {
                return ResourceManager.GetString("Electroclash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronic.
        /// </summary>
        public static string Electronic {
            get {
                return ResourceManager.GetString("Electronic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emo.
        /// </summary>
        public static string Emo {
            get {
                return ResourceManager.GetString("Emo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethnic.
        /// </summary>
        public static string Ethnic {
            get {
                return ResourceManager.GetString("Ethnic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eurodance.
        /// </summary>
        public static string Eurodance {
            get {
                return ResourceManager.GetString("Eurodance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euro-House.
        /// </summary>
        public static string EuroHouse {
            get {
                return ResourceManager.GetString("EuroHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euro-Techno.
        /// </summary>
        public static string EuroTechno {
            get {
                return ResourceManager.GetString("EuroTechno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimental.
        /// </summary>
        public static string Experimental {
            get {
                return ResourceManager.GetString("Experimental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast-Fusion.
        /// </summary>
        public static string FastFusion {
            get {
                return ResourceManager.GetString("FastFusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folk.
        /// </summary>
        public static string Folk {
            get {
                return ResourceManager.GetString("Folk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folklore.
        /// </summary>
        public static string Folklore {
            get {
                return ResourceManager.GetString("Folklore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folk-Rock.
        /// </summary>
        public static string FolkRock {
            get {
                return ResourceManager.GetString("FolkRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freestyle.
        /// </summary>
        public static string Freestyle {
            get {
                return ResourceManager.GetString("Freestyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funk.
        /// </summary>
        public static string Funk {
            get {
                return ResourceManager.GetString("Funk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fusion.
        /// </summary>
        public static string Fusion {
            get {
                return ResourceManager.GetString("Fusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gangsta.
        /// </summary>
        public static string Gangsta {
            get {
                return ResourceManager.GetString("Gangsta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garage.
        /// </summary>
        public static string Garage {
            get {
                return ResourceManager.GetString("Garage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garage Rock.
        /// </summary>
        public static string GarageRock {
            get {
                return ResourceManager.GetString("GarageRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G-Funk.
        /// </summary>
        public static string GFunk {
            get {
                return ResourceManager.GetString("GFunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global.
        /// </summary>
        public static string Global {
            get {
                return ResourceManager.GetString("Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goa.
        /// </summary>
        public static string Goa {
            get {
                return ResourceManager.GetString("Goa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gospel.
        /// </summary>
        public static string Gospel {
            get {
                return ResourceManager.GetString("Gospel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gothic.
        /// </summary>
        public static string Gothic {
            get {
                return ResourceManager.GetString("Gothic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gothic Rock.
        /// </summary>
        public static string GothicRock {
            get {
                return ResourceManager.GetString("GothicRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grunge.
        /// </summary>
        public static string Grunge {
            get {
                return ResourceManager.GetString("Grunge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardcore.
        /// </summary>
        public static string Hardcore {
            get {
                return ResourceManager.GetString("Hardcore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard Rock.
        /// </summary>
        public static string HardRock {
            get {
                return ResourceManager.GetString("HardRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy Metal.
        /// </summary>
        public static string HeavyMetal {
            get {
                return ResourceManager.GetString("HeavyMetal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hip-Hop.
        /// </summary>
        public static string HipHop {
            get {
                return ResourceManager.GetString("HipHop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House.
        /// </summary>
        public static string House {
            get {
                return ResourceManager.GetString("House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humor.
        /// </summary>
        public static string Humor {
            get {
                return ResourceManager.GetString("Humor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDM.
        /// </summary>
        public static string IDM {
            get {
                return ResourceManager.GetString("IDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illbient.
        /// </summary>
        public static string Illbient {
            get {
                return ResourceManager.GetString("Illbient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indie.
        /// </summary>
        public static string Indie {
            get {
                return ResourceManager.GetString("Indie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indie Rock.
        /// </summary>
        public static string IndieRock {
            get {
                return ResourceManager.GetString("IndieRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industrial.
        /// </summary>
        public static string Industrial {
            get {
                return ResourceManager.GetString("Industrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industro-Goth.
        /// </summary>
        public static string IndustroGoth {
            get {
                return ResourceManager.GetString("IndustroGoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrumental Pop.
        /// </summary>
        public static string InstrPop {
            get {
                return ResourceManager.GetString("InstrPop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrumental Rock.
        /// </summary>
        public static string InstrRock {
            get {
                return ResourceManager.GetString("InstrRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrumental.
        /// </summary>
        public static string Instrumental {
            get {
                return ResourceManager.GetString("Instrumental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jam Band.
        /// </summary>
        public static string JamBand {
            get {
                return ResourceManager.GetString("JamBand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jazz.
        /// </summary>
        public static string Jazz {
            get {
                return ResourceManager.GetString("Jazz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jazz+Funk.
        /// </summary>
        public static string JazzFunk {
            get {
                return ResourceManager.GetString("JazzFunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPop.
        /// </summary>
        public static string JPop {
            get {
                return ResourceManager.GetString("JPop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jungle.
        /// </summary>
        public static string Jungle {
            get {
                return ResourceManager.GetString("Jungle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krautrock.
        /// </summary>
        public static string Krautrock {
            get {
                return ResourceManager.GetString("Krautrock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latin.
        /// </summary>
        public static string Latin {
            get {
                return ResourceManager.GetString("Latin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leftfield.
        /// </summary>
        public static string Leftfield {
            get {
                return ResourceManager.GetString("Leftfield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo-Fi.
        /// </summary>
        public static string LoFi {
            get {
                return ResourceManager.GetString("LoFi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lounge.
        /// </summary>
        public static string Lounge {
            get {
                return ResourceManager.GetString("Lounge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Math Rock.
        /// </summary>
        public static string MathRock {
            get {
                return ResourceManager.GetString("MathRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meditative.
        /// </summary>
        public static string Meditative {
            get {
                return ResourceManager.GetString("Meditative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merengue.
        /// </summary>
        public static string Merengue {
            get {
                return ResourceManager.GetString("Merengue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metal.
        /// </summary>
        public static string Metal {
            get {
                return ResourceManager.GetString("Metal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musical.
        /// </summary>
        public static string Musical {
            get {
                return ResourceManager.GetString("Musical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Folk.
        /// </summary>
        public static string NationalFolk {
            get {
                return ResourceManager.GetString("NationalFolk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native American.
        /// </summary>
        public static string NativeAm {
            get {
                return ResourceManager.GetString("NativeAm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neoclassical.
        /// </summary>
        public static string Neoclassical {
            get {
                return ResourceManager.GetString("Neoclassical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Deutsche Welle.
        /// </summary>
        public static string NeueDeutscheWelle {
            get {
                return ResourceManager.GetString("NeueDeutscheWelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Age.
        /// </summary>
        public static string NewAge {
            get {
                return ResourceManager.GetString("NewAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Romantic.
        /// </summary>
        public static string NewRomantic {
            get {
                return ResourceManager.GetString("NewRomantic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Wave.
        /// </summary>
        public static string NewWave {
            get {
                return ResourceManager.GetString("NewWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise.
        /// </summary>
        public static string Noise {
            get {
                return ResourceManager.GetString("Noise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu-Breakz.
        /// </summary>
        public static string NuBreakz {
            get {
                return ResourceManager.GetString("NuBreakz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oldies.
        /// </summary>
        public static string Oldies {
            get {
                return ResourceManager.GetString("Oldies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opera.
        /// </summary>
        public static string Opera {
            get {
                return ResourceManager.GetString("Opera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other genre.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podcast.
        /// </summary>
        public static string Podcast {
            get {
                return ResourceManager.GetString("Podcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polka.
        /// </summary>
        public static string Polka {
            get {
                return ResourceManager.GetString("Polka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polsk Punk.
        /// </summary>
        public static string PolskPunk {
            get {
                return ResourceManager.GetString("PolskPunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pop.
        /// </summary>
        public static string Pop {
            get {
                return ResourceManager.GetString("Pop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pop-Folk.
        /// </summary>
        public static string PopFolk {
            get {
                return ResourceManager.GetString("PopFolk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pop-Funk.
        /// </summary>
        public static string PopFunk {
            get {
                return ResourceManager.GetString("PopFunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porn Groove.
        /// </summary>
        public static string PornGroove {
            get {
                return ResourceManager.GetString("PornGroove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-Punk.
        /// </summary>
        public static string PostPunk {
            get {
                return ResourceManager.GetString("PostPunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-Rock.
        /// </summary>
        public static string PostRock {
            get {
                return ResourceManager.GetString("PostRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Ballad.
        /// </summary>
        public static string PowerBallad {
            get {
                return ResourceManager.GetString("PowerBallad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pranks.
        /// </summary>
        public static string Pranks {
            get {
                return ResourceManager.GetString("Pranks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primus.
        /// </summary>
        public static string Primus {
            get {
                return ResourceManager.GetString("Primus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progressive Rock.
        /// </summary>
        public static string ProgRock {
            get {
                return ResourceManager.GetString("ProgRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psybient.
        /// </summary>
        public static string Psybient {
            get {
                return ResourceManager.GetString("Psybient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psychedelic.
        /// </summary>
        public static string Psychedelic {
            get {
                return ResourceManager.GetString("Psychedelic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psychedelic Rock.
        /// </summary>
        public static string PsychRock {
            get {
                return ResourceManager.GetString("PsychRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psytrance.
        /// </summary>
        public static string Psytrance {
            get {
                return ResourceManager.GetString("Psytrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punk.
        /// </summary>
        public static string Punk {
            get {
                return ResourceManager.GetString("Punk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punk Rock.
        /// </summary>
        public static string PunkRock {
            get {
                return ResourceManager.GetString("PunkRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rap.
        /// </summary>
        public static string Rap {
            get {
                return ResourceManager.GetString("Rap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rave.
        /// </summary>
        public static string Rave {
            get {
                return ResourceManager.GetString("Rave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R&amp;B.
        /// </summary>
        public static string RB {
            get {
                return ResourceManager.GetString("RB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reggae.
        /// </summary>
        public static string Reggae {
            get {
                return ResourceManager.GetString("Reggae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retro.
        /// </summary>
        public static string Retro {
            get {
                return ResourceManager.GetString("Retro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revival.
        /// </summary>
        public static string Revival {
            get {
                return ResourceManager.GetString("Revival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhythmic Soul.
        /// </summary>
        public static string RhythmicSoul {
            get {
                return ResourceManager.GetString("RhythmicSoul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock.
        /// </summary>
        public static string Rock {
            get {
                return ResourceManager.GetString("Rock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock &amp; Roll.
        /// </summary>
        public static string RockRoll {
            get {
                return ResourceManager.GetString("RockRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salsa.
        /// </summary>
        public static string Salsa {
            get {
                return ResourceManager.GetString("Salsa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samba.
        /// </summary>
        public static string Samba {
            get {
                return ResourceManager.GetString("Samba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satire.
        /// </summary>
        public static string Satire {
            get {
                return ResourceManager.GetString("Satire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoegaze.
        /// </summary>
        public static string Shoegaze {
            get {
                return ResourceManager.GetString("Shoegaze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showtunes.
        /// </summary>
        public static string Showtunes {
            get {
                return ResourceManager.GetString("Showtunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ska.
        /// </summary>
        public static string Ska {
            get {
                return ResourceManager.GetString("Ska", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow Jam.
        /// </summary>
        public static string SlowJam {
            get {
                return ResourceManager.GetString("SlowJam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow Rock.
        /// </summary>
        public static string SlowRock {
            get {
                return ResourceManager.GetString("SlowRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonata.
        /// </summary>
        public static string Sonata {
            get {
                return ResourceManager.GetString("Sonata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soul.
        /// </summary>
        public static string Soul {
            get {
                return ResourceManager.GetString("Soul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Clip.
        /// </summary>
        public static string SoundClip {
            get {
                return ResourceManager.GetString("SoundClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soundtrack.
        /// </summary>
        public static string Soundtrack {
            get {
                return ResourceManager.GetString("Soundtrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Southern Rock.
        /// </summary>
        public static string SouthernRock {
            get {
                return ResourceManager.GetString("SouthernRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space.
        /// </summary>
        public static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space Rock.
        /// </summary>
        public static string SpaceRock {
            get {
                return ResourceManager.GetString("SpaceRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech.
        /// </summary>
        public static string Speech {
            get {
                return ResourceManager.GetString("Speech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swing.
        /// </summary>
        public static string Swing {
            get {
                return ResourceManager.GetString("Swing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symphony.
        /// </summary>
        public static string Symphony {
            get {
                return ResourceManager.GetString("Symphony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symphonic Rock.
        /// </summary>
        public static string SymphRock {
            get {
                return ResourceManager.GetString("SymphRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synthpop.
        /// </summary>
        public static string Synthpop {
            get {
                return ResourceManager.GetString("Synthpop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tango.
        /// </summary>
        public static string Tango {
            get {
                return ResourceManager.GetString("Tango", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Techno.
        /// </summary>
        public static string Techno {
            get {
                return ResourceManager.GetString("Techno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Techno-Industrial.
        /// </summary>
        public static string TechnoIndustr {
            get {
                return ResourceManager.GetString("TechnoIndustr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terror.
        /// </summary>
        public static string Terror {
            get {
                return ResourceManager.GetString("Terror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thrash Metal.
        /// </summary>
        public static string ThrashMetal {
            get {
                return ResourceManager.GetString("ThrashMetal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 40.
        /// </summary>
        public static string Top40 {
            get {
                return ResourceManager.GetString("Top40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailer.
        /// </summary>
        public static string Trailer {
            get {
                return ResourceManager.GetString("Trailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trance.
        /// </summary>
        public static string Trance {
            get {
                return ResourceManager.GetString("Trance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tribal.
        /// </summary>
        public static string Tribal {
            get {
                return ResourceManager.GetString("Tribal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip-Hop.
        /// </summary>
        public static string TripHop {
            get {
                return ResourceManager.GetString("TripHop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trop Rock.
        /// </summary>
        public static string TropRock {
            get {
                return ResourceManager.GetString("TropRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown genre: {0}.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vocal.
        /// </summary>
        public static string Vocal {
            get {
                return ResourceManager.GetString("Vocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Music.
        /// </summary>
        public static string WorldMusic {
            get {
                return ResourceManager.GetString("WorldMusic", resourceCulture);
            }
        }
    }
}
