//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgEitilt.CardCatalog.Strings {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgEitilt.CardCatalog.Strings.Exceptions", typeof(Exceptions).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata tag field types must extend TagField.
        /// </summary>
        internal static string ExtendFieldType {
            get {
                return ResourceManager.GetString("ExtendFieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If a TagFieldAttribute does not declare a Format, at least one enclosing type must have an associated MetadataFormatAttribute.
        /// </summary>
        internal static string NoFieldEnclosingFormatName {
            get {
                return ResourceManager.GetString("NoFieldEnclosingFormatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No explicit format name was passed, and the type has no attribute to infer it from.
        /// </summary>
        internal static string NoFormatName {
            get {
                return ResourceManager.GetString("NoFormatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata header-parsing functions must not be abstract.
        /// </summary>
        internal static string ParseFunctionAbstract {
            get {
                return ResourceManager.GetString("ParseFunctionAbstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata header-parsing functions must be static.
        /// </summary>
        internal static string ParseFunctionNonstatic {
            get {
                return ResourceManager.GetString("ParseFunctionNonstatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata header-parsing functions must be able to take only an IEnumerable&lt;byte&gt;.
        /// </summary>
        internal static string ParseFunctionParameters {
            get {
                return ResourceManager.GetString("ParseFunctionParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata header-parsing functions must not be private.
        /// </summary>
        internal static string ParseFunctionPrivate {
            get {
                return ResourceManager.GetString("ParseFunctionPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata header-parsing functions must return an empty instance of their type.
        /// </summary>
        internal static string ParseFunctionReturn {
            get {
                return ResourceManager.GetString("ParseFunctionReturn", resourceCulture);
            }
        }
    }
}
